name: cd

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: setup go
          uses: actions/setup-go@v4

        - name: build prod
          run: bash ./scripts/buildprod.sh

